/**
 * Rolex reference guide data — model lines, production eras, and quick specs for buyers and collectors.
 * Reference numbers and eras are summarized from publicly documented Rolex production; not exhaustive.
 */

export type RolexReferenceEntry = {
  family: string;
  reference: string;
  model: string;
  production: string;
  description: string;
};

/** Filter pill values (excluding synthetic "All") */
export const ROLEX_REFERENCE_FAMILIES = [
  'Submariner',
  'GMT-Master',
  'Daytona',
  'Explorer',
  'Sea-Dweller',
  'Datejust',
  'Day-Date',
  'Oyster Perpetual',
  'Milgauss',
  'Air-King',
  'Yacht-Master',
  'Cellini',
  'Vintage',
] as const;

export type RolexReferenceFamily = (typeof ROLEX_REFERENCE_FAMILIES)[number];

export const rolexReferences: RolexReferenceEntry[] = [
  { family: 'Submariner', reference: '6204', model: 'Submariner', production: '1953–1954', description: '37mm steel, early no-crown-guard diver, 100m WR' },
  { family: 'Submariner', reference: '6205', model: 'Submariner', production: '1954–1955', description: 'Early steel no-guard Sub, small crown, gilt dial' },
  { family: 'Submariner', reference: '6200', model: 'Submariner', production: '1954–1956', description: '37mm Big Crown no-guards, 200m WR, Explorer dial' },
  { family: 'Submariner', reference: '6536', model: 'Submariner', production: '1955–1959', description: '38mm small-crown no-guards, gilt dial, 100m WR' },
  { family: 'Submariner', reference: '6538', model: 'Submariner', production: '1956–1959', description: '38mm Big Crown no-guards, 200m, James Bond Sub' },
  { family: 'Submariner', reference: '5508', model: 'Submariner', production: '1958–1962', description: '38mm small-crown no-guards, gilt dial, 100m WR' },
  { family: 'Submariner', reference: '5512', model: 'Submariner', production: '1959–1980', description: '40mm steel, crown guards, COSC chronometer text' },
  { family: 'Submariner', reference: '5513', model: 'Submariner', production: '1962–1989', description: '40mm steel no-date Sub, non-COSC, classic gilt and matte dials' },
  { family: 'Submariner', reference: '5514', model: 'Submariner COMEX', production: 'c.1972–1977', description: '40mm COMEX-issued Sub with helium valve' },
  { family: 'Submariner', reference: '5517', model: 'Submariner MilSub', production: 'c.1970s', description: '40mm British MOD spec, sword hands, fixed bars' },
  { family: 'Submariner', reference: '1680', model: 'Submariner Date', production: '1969–1979', description: '40mm first date Sub, acrylic, some Red Sub dials' },
  { family: 'Submariner', reference: '16800', model: 'Submariner Date', production: '1979–1986', description: '40mm sapphire quickset, matte to gloss dial transition' },
  { family: 'Submariner', reference: '168000', model: 'Submariner Date', production: '1986–1987', description: 'Short-run 904L steel transitional 16800' },
  { family: 'Submariner', reference: '16610', model: 'Submariner Date', production: '1988–2010', description: '40mm steel aluminum bezel workhorse date Sub' },
  { family: 'Submariner', reference: '14060', model: 'Submariner', production: '1990–2002', description: '40mm steel no-date tritium then Luminova' },
  { family: 'Submariner', reference: '14060M', model: 'Submariner', production: '2002–2012', description: '40mm updated no-date later COSC 4-liner' },
  { family: 'Submariner', reference: '16610LV', model: 'Submariner Date "Kermit"', production: '2003–2010', description: '40mm steel green bezel 50th anniversary' },
  { family: 'Submariner', reference: '16613', model: 'Submariner Date', production: '1988–2010', description: '40mm two-tone steel and yellow gold Bluesy' },
  { family: 'Submariner', reference: '16618', model: 'Submariner Date', production: '1988–2010', description: '40mm solid yellow gold Sub Date' },
  { family: 'Submariner', reference: '116610LN', model: 'Submariner Date', production: '2010–2020', description: '40mm maxi case ceramic bezel black' },
  { family: 'Submariner', reference: '116610LV', model: 'Submariner Date "Hulk"', production: '2010–2020', description: '40mm ceramic green dial and bezel' },
  { family: 'Submariner', reference: '114060', model: 'Submariner', production: '2012–2020', description: '40mm ceramic no-date maxi case' },
  { family: 'Submariner', reference: '116619LB', model: 'Submariner Date "Smurf"', production: '2008–2020', description: '40mm white gold blue dial' },
  { family: 'Submariner', reference: '126610LN', model: 'Submariner Date', production: '2020–present', description: '41mm steel date ceramic new caliber' },
  { family: 'Submariner', reference: '126610LV', model: 'Submariner Date "Cermit"', production: '2020–present', description: '41mm steel black dial green bezel' },
  { family: 'Submariner', reference: '124060', model: 'Submariner', production: '2020–present', description: '41mm steel no-date slimmer lugs' },

  { family: 'GMT-Master', reference: '6542', model: 'GMT-Master', production: '1954–1959', description: '38mm steel Bakelite Pepsi bezel no crown guards' },
  { family: 'GMT-Master', reference: '1675', model: 'GMT-Master', production: '1959–1980', description: '40mm crown guards long-running Pepsi classic' },
  { family: 'GMT-Master', reference: '16750', model: 'GMT-Master', production: '1981–1988', description: '40mm quickset matte to gloss dial Pepsi' },
  { family: 'GMT-Master', reference: '16753', model: 'GMT-Master', production: '1970s–1980s', description: '40mm two-tone Root Beer brown and yellow' },
  { family: 'GMT-Master', reference: '16758', model: 'GMT-Master', production: '1970s–1980s', description: '40mm yellow gold nipple dial Pepsi and brown' },
  { family: 'GMT-Master', reference: '16700', model: 'GMT-Master', production: '1988–1999', description: '40mm last non-independent-hand GMT-Master' },
  { family: 'GMT-Master', reference: '16760', model: 'GMT-Master II "Fat Lady"', production: '1983–1988', description: '40mm first GMT-Master II Coke bezel' },
  { family: 'GMT-Master', reference: '16710', model: 'GMT-Master II', production: '1989–2007', description: '40mm aluminum Pepsi Coke and black bezel variants' },
  { family: 'GMT-Master', reference: '116710LN', model: 'GMT-Master II', production: '2007–2019', description: '40mm ceramic bezel green GMT hand' },
  { family: 'GMT-Master', reference: '116710BLNR', model: 'GMT-Master II "Batman"', production: '2013–2019', description: '40mm black and blue ceramic bezel' },
  { family: 'GMT-Master', reference: '116718LN', model: 'GMT-Master II', production: '2005–2019', description: '40mm yellow gold green dial anniversary' },
  { family: 'GMT-Master', reference: '116719BLRO', model: 'GMT-Master II', production: '2014–2018', description: '40mm white gold ceramic Pepsi' },
  { family: 'GMT-Master', reference: '126710BLRO', model: 'GMT-Master II "Pepsi"', production: '2018–present', description: '40mm steel Jubilee ceramic Pepsi' },
  { family: 'GMT-Master', reference: '126710BLNR', model: 'GMT-Master II "Batman/Batgirl"', production: '2019–present', description: '40mm steel Jubilee and Oyster' },
  { family: 'GMT-Master', reference: '126711CHNR', model: 'GMT-Master II "Root Beer"', production: '2018–present', description: '40mm two-tone ceramic' },
  { family: 'GMT-Master', reference: '126715CHNR', model: 'GMT-Master II "Root Beer"', production: '2018–present', description: '40mm Everose gold' },
  { family: 'GMT-Master', reference: '126720VTNR', model: 'GMT-Master II "Sprite"', production: '2022–present', description: '40mm steel green and black left crown' },

  { family: 'Daytona', reference: '6239', model: 'Cosmograph Daytona', production: '1963–1969', description: '37mm steel pump pushers Paul Newman exotic dials' },
  { family: 'Daytona', reference: '6241', model: 'Cosmograph Daytona', production: '1965–1969', description: '37mm steel black acrylic bezel pump pushers' },
  { family: 'Daytona', reference: '6262', model: 'Cosmograph Daytona', production: '1969–1972', description: '37mm steel Valjoux 727 pump pushers' },
  { family: 'Daytona', reference: '6263', model: 'Cosmograph Daytona', production: '1969–1987', description: '37mm steel screw-down pushers black bezel' },
  { family: 'Daytona', reference: '6264', model: 'Cosmograph Daytona', production: '1969–1972', description: '37mm steel pump pushers black bezel' },
  { family: 'Daytona', reference: '6265', model: 'Cosmograph Daytona', production: '1969–1987', description: '37mm steel screw-down pushers metal bezel' },
  { family: 'Daytona', reference: '16520', model: 'Cosmograph Daytona', production: '1988–2000', description: '40mm steel Zenith automatic steel bezel' },
  { family: 'Daytona', reference: '16523', model: 'Cosmograph Daytona', production: '1988–2000', description: '40mm two-tone Zenith Daytona' },
  { family: 'Daytona', reference: '16528', model: 'Cosmograph Daytona', production: '1988–2000', description: '40mm yellow gold Zenith Daytona' },
  { family: 'Daytona', reference: '116520', model: 'Cosmograph Daytona', production: '2000–2016', description: '40mm steel in-house 4130 steel bezel' },
  { family: 'Daytona', reference: '116523', model: 'Cosmograph Daytona', production: '2000–2016', description: '40mm two-tone in-house movement' },
  { family: 'Daytona', reference: '116528', model: 'Cosmograph Daytona', production: '2000–2016', description: '40mm yellow gold in-house' },
  { family: 'Daytona', reference: '116500LN', model: 'Cosmograph Daytona', production: '2016–2023', description: '40mm steel ceramic bezel black and white dial' },
  { family: 'Daytona', reference: '126500LN', model: 'Cosmograph Daytona', production: '2023–present', description: '40mm steel updated case and movement ceramic bezel' },
  { family: 'Daytona', reference: '116506', model: 'Cosmograph Daytona', production: '2013–present', description: '40mm platinum ice-blue dial brown bezel' },
  { family: 'Daytona', reference: '116505', model: 'Cosmograph Daytona', production: '2008–present', description: '40mm Everose gold Oysterflex and bracelet options' },

  { family: 'Explorer', reference: '6150', model: 'Explorer', production: '1953–1955', description: '36mm early 3-6-9 dial Oyster proto-Explorer' },
  { family: 'Explorer', reference: '6610', model: 'Explorer', production: '1955–1959', description: '36mm gilt 3-6-9 improved depth rating' },
  { family: 'Explorer', reference: '1016', model: 'Explorer', production: '1963–1989', description: '36mm classic matte 3-6-9 100m WR icon' },
  { family: 'Explorer', reference: '14270', model: 'Explorer', production: '1989–2001', description: '36mm sapphire applied markers modern look' },
  { family: 'Explorer', reference: '114270', model: 'Explorer', production: '2001–2010', description: '36mm updated 3130 movement' },
  { family: 'Explorer', reference: '214270', model: 'Explorer', production: '2010–2021', description: '39mm case later luminous numerals' },
  { family: 'Explorer', reference: '124270', model: 'Explorer', production: '2021–present', description: '36mm new 3230 movement modern bracelet' },
  { family: 'Explorer', reference: '1655', model: 'Explorer II "Steve McQueen"', production: '1971–1985', description: '39mm steel fixed bezel orange hand Freccione' },
  { family: 'Explorer', reference: '16550', model: 'Explorer II', production: '1985–1989', description: '40mm white and black dial transitional sapphire' },
  { family: 'Explorer', reference: '16570', model: 'Explorer II', production: '1989–2011', description: '40mm polar and black 3185 and 3186 calibers' },
  { family: 'Explorer', reference: '216570', model: 'Explorer II', production: '2011–2021', description: '42mm maxi case orange 24-hour hand' },
  { family: 'Explorer', reference: '226570', model: 'Explorer II', production: '2021–present', description: '42mm updated movement 3285 subtle tweaks' },

  { family: 'Sea-Dweller', reference: '1665', model: 'Sea-Dweller "Double Red"', production: '1967–1983', description: '40mm helium valve Double Red then Great White' },
  { family: 'Sea-Dweller', reference: '16660', model: 'Sea-Dweller "Triple Six"', production: '1978–1989', description: '40mm sapphire 1220m WR' },
  { family: 'Sea-Dweller', reference: '16600', model: 'Sea-Dweller', production: '1989–2009', description: '40mm steel classic professional diver' },
  { family: 'Sea-Dweller', reference: '116600', model: 'Sea-Dweller', production: '2014–2017', description: '40mm ceramic bezel no cyclops modern reissue' },
  { family: 'Sea-Dweller', reference: '126600', model: 'Sea-Dweller', production: '2017–present', description: '43mm cyclops date red Sea-Dweller text' },
  { family: 'Sea-Dweller', reference: '126603', model: 'Sea-Dweller', production: '2019–present', description: '43mm two-tone steel and yellow gold' },
  { family: 'Sea-Dweller', reference: '116660', model: 'Deepsea', production: '2008–2018', description: '44mm 3900m WR Ringlock case D-Blue and black dials' },
  { family: 'Sea-Dweller', reference: '126660', model: 'Deepsea', production: '2018–2022', description: '44mm updated 3235 wider bracelet' },
  { family: 'Sea-Dweller', reference: '136660', model: 'Deepsea', production: '2022–present', description: '44mm incremental update 3235 D-Blue and black' },

  { family: 'Datejust', reference: '4467', model: 'Datejust', production: '1945–late 1940s', description: '36mm Jubilee-launch coin-edge bezel no Datejust text' },
  { family: 'Datejust', reference: '6305', model: 'Datejust', production: '1950s', description: '36mm early DJ with fluted bezel' },
  { family: 'Datejust', reference: '6518', model: 'Datejust', production: '1950s', description: '36mm steel and gold early cyclops generations' },
  { family: 'Datejust', reference: '1600', model: 'Datejust', production: '1960s–1970s', description: '36mm smooth bezel pie-pan dials' },
  { family: 'Datejust', reference: '1601', model: 'Datejust', production: '1960s–1970s', description: '36mm fluted bezel pie-pan acrylic crystal' },
  { family: 'Datejust', reference: '1603', model: 'Datejust', production: '1960s–1970s', description: '36mm engine-turned bezel pie-pan' },
  { family: 'Datejust', reference: '16014', model: 'Datejust', production: '1977–1980s', description: '36mm steel and white gold quickset 3035' },
  { family: 'Datejust', reference: '16030', model: 'Datejust', production: '1977–1980s', description: '36mm engine-turned quickset' },
  { family: 'Datejust', reference: '16013', model: 'Datejust', production: '1977–1980s', description: '36mm two-tone fluted bezel 3035' },
  { family: 'Datejust', reference: '16200', model: 'Datejust', production: '1988–2000s', description: '36mm smooth bezel sapphire 3135' },
  { family: 'Datejust', reference: '16220', model: 'Datejust', production: '1988–2000s', description: '36mm engine-turned sapphire' },
  { family: 'Datejust', reference: '16233', model: 'Datejust', production: '1988–2000s', description: '36mm two-tone fluted 3135' },
  { family: 'Datejust', reference: '16234', model: 'Datejust', production: '1988–2000s', description: '36mm steel and white gold fluted' },
  { family: 'Datejust', reference: '116200', model: 'Datejust', production: '2004–2018', description: '36mm smooth bezel solid bracelet' },
  { family: 'Datejust', reference: '116234', model: 'Datejust', production: '2004–2018', description: '36mm steel and white gold fluted updated case' },
  { family: 'Datejust', reference: '116233', model: 'Datejust', production: '2004–2018', description: '36mm two-tone solid links 3135' },
  { family: 'Datejust', reference: '126200', model: 'Datejust', production: '2018–present', description: '36mm smooth bezel 3235 movement' },
  { family: 'Datejust', reference: '126234', model: 'Datejust', production: '2018–present', description: '36mm fluted steel and white gold updated case' },
  { family: 'Datejust', reference: '116300', model: 'Datejust II', production: '2009–2016', description: '41mm smooth bezel broad lugs' },
  { family: 'Datejust', reference: '116334', model: 'Datejust II', production: '2009–2016', description: '41mm steel and white gold fluted' },
  { family: 'Datejust', reference: '126300', model: 'Datejust 41', production: '2016–present', description: '41mm smooth bezel slimmer profile' },
  { family: 'Datejust', reference: '126334', model: 'Datejust 41', production: '2016–present', description: '41mm fluted steel and white gold' },

  { family: 'Day-Date', reference: '6510', model: 'Day-Date', production: '1956–1957', description: '36mm gold first day and date display' },
  { family: 'Day-Date', reference: '6511', model: 'Day-Date', production: '1956–1957', description: '36mm early improved movement' },
  { family: 'Day-Date', reference: '1803', model: 'Day-Date', production: '1960–1970s', description: '36mm pie-pan dial fluted bezel classic vintage' },
  { family: 'Day-Date', reference: '1804', model: 'Day-Date', production: '1960s', description: '36mm diamond bezel version of 1803' },
  { family: 'Day-Date', reference: '1807', model: 'Day-Date', production: '1960s', description: '36mm bark bezel and bracelet texture' },
  { family: 'Day-Date', reference: '18038', model: 'Day-Date', production: '1977–1980s', description: '36mm sapphire quickset 3055' },
  { family: 'Day-Date', reference: '18238', model: 'Day-Date', production: '1988–2000', description: '36mm double-quickset 3155 yellow gold' },
  { family: 'Day-Date', reference: '18239', model: 'Day-Date', production: '1988–2000', description: '36mm white gold double-quickset' },
  { family: 'Day-Date', reference: '118238', model: 'Day-Date', production: '2000–2015', description: '36mm heavier solid bracelet yellow gold' },
  { family: 'Day-Date', reference: '118239', model: 'Day-Date', production: '2000–2015', description: '36mm white gold solid end links' },
  { family: 'Day-Date', reference: '218206', model: 'Day-Date II', production: '2008–2015', description: '41mm platinum large case President' },
  { family: 'Day-Date', reference: '218238', model: 'Day-Date II', production: '2008–2015', description: '41mm yellow gold super-case' },
  { family: 'Day-Date', reference: '228235', model: 'Day-Date 40', production: '2015–present', description: '40mm Everose gold 3255 movement' },
  { family: 'Day-Date', reference: '228238', model: 'Day-Date 40', production: '2015–present', description: '40mm yellow gold fluted bezel' },
  { family: 'Day-Date', reference: '228239', model: 'Day-Date 40', production: '2015–present', description: '40mm white gold latest President' },

  { family: 'Oyster Perpetual', reference: '1002', model: 'Oyster Perpetual', production: '1950s–1960s', description: '34mm steel clean 3-hander' },
  { family: 'Oyster Perpetual', reference: '1018', model: 'Oyster Perpetual', production: '1950s–1960s', description: '36mm anti-magnetic style OP' },
  { family: 'Oyster Perpetual', reference: '5500', model: 'Oyster Perpetual', production: '1957–1990', description: '34mm long-running entry OP' },
  { family: 'Oyster Perpetual', reference: '14203', model: 'Oyster Perpetual', production: '1990s–2000s', description: '34mm two-tone smooth bezel' },
  { family: 'Oyster Perpetual', reference: '14233', model: 'Oyster Perpetual', production: '1990s–2000s', description: '34mm two-tone fluted bezel' },
  { family: 'Oyster Perpetual', reference: '114200', model: 'Oyster Perpetual', production: '2007–2014', description: '34mm modern OP smooth bezel' },
  { family: 'Oyster Perpetual', reference: '114300', model: 'Oyster Perpetual', production: '2015–2020', description: '39mm steel colored dials' },
  { family: 'Oyster Perpetual', reference: '124200', model: 'Oyster Perpetual', production: '2020–present', description: '34mm updated 3230 movement' },
  { family: 'Oyster Perpetual', reference: '124300', model: 'Oyster Perpetual', production: '2020–present', description: '41mm colorful Stella-style dials' },
  { family: 'Oyster Perpetual', reference: '126000', model: 'Oyster Perpetual', production: '2020–present', description: '36mm popular colorful dials' },

  { family: 'Milgauss', reference: '6543', model: 'Milgauss', production: '1954–1956', description: '38mm early antimagnetic prototype-style' },
  { family: 'Milgauss', reference: '6541', model: 'Milgauss', production: '1956–1960', description: '38mm lightning-bolt seconds honeycomb dial' },
  { family: 'Milgauss', reference: '1019', model: 'Milgauss', production: '1960–1988', description: '38mm toned-down scientist\'s watch smooth bezel' },
  { family: 'Milgauss', reference: '116400', model: 'Milgauss', production: '2007–2014', description: '40mm steel clear crystal orange lightning hand' },
  { family: 'Milgauss', reference: '116400GV', model: 'Milgauss', production: '2007–2023', description: '40mm green sapphire GV black or Z-Blue dial' },

  { family: 'Air-King', reference: '4925', model: 'Air-King', production: '1945–late 1940s', description: '34mm early Air series pilot watch' },
  { family: 'Air-King', reference: '4499', model: 'Air-King', production: 'late 1940s–1950s', description: '34mm manual-wind Air-King' },
  { family: 'Air-King', reference: '6552', model: 'Air-King', production: '1950s', description: '34mm early automatic Cal.1030' },
  { family: 'Air-King', reference: '5500', model: 'Air-King', production: '1958–1988', description: '34mm archetypal Air-King long production' },
  { family: 'Air-King', reference: '14000', model: 'Air-King', production: '1989–1999', description: '34mm sapphire Cal.3000' },
  { family: 'Air-King', reference: '14010', model: 'Air-King', production: '1989–1999', description: '34mm engine-turned bezel variant' },
  { family: 'Air-King', reference: '114200', model: 'Air-King', production: '2007–2014', description: '34mm updated case and dial' },
  { family: 'Air-King', reference: '116900', model: 'Air-King', production: '2016–2022', description: '40mm Milgauss-style case instrument dial' },
  { family: 'Air-King', reference: '126900', model: 'Air-King', production: '2022–present', description: '40mm crown-guard case improved bracelet' },

  { family: 'Yacht-Master', reference: '16628', model: 'Yacht-Master', production: '1992–2005', description: '40mm yellow gold sport-lux bezel' },
  { family: 'Yacht-Master', reference: '16622', model: 'Yacht-Master', production: '1999–2012', description: '40mm steel with platinum bezel and dial' },
  { family: 'Yacht-Master', reference: '16623', model: 'Yacht-Master', production: '2005–2012', description: '40mm two-tone steel and yellow gold' },
  { family: 'Yacht-Master', reference: '116622', model: 'Yacht-Master', production: '2012–2019', description: '40mm platinum bezel sunburst dials' },
  { family: 'Yacht-Master', reference: '116621', model: 'Yacht-Master', production: '2016–2022', description: '40mm steel and Everose two-tone' },
  { family: 'Yacht-Master', reference: '116655', model: 'Yacht-Master', production: '2015–2023', description: '40mm Everose on Oysterflex black Cerachrom' },
  { family: 'Yacht-Master', reference: '126622', model: 'Yacht-Master', production: '2019–present', description: '40mm updated steel and platinum' },
  { family: 'Yacht-Master', reference: '126655', model: 'Yacht-Master', production: '2019–present', description: '40mm Everose Oysterflex updated movement' },
  { family: 'Yacht-Master', reference: '226659', model: 'Yacht-Master', production: '2019–present', description: '42mm white gold Oysterflex black bezel' },
  { family: 'Yacht-Master', reference: '116688', model: 'Yacht-Master II', production: '2007–present', description: '44mm yellow gold regatta countdown' },
  { family: 'Yacht-Master', reference: '116689', model: 'Yacht-Master II', production: '2007–present', description: '44mm white gold platinum bezel' },
  { family: 'Yacht-Master', reference: '116681', model: 'Yacht-Master II', production: '2013–present', description: '44mm two-tone steel and yellow gold' },
  { family: 'Yacht-Master', reference: '116680', model: 'Yacht-Master II', production: '2013–present', description: '44mm full steel regatta chronograph' },

  { family: 'Cellini', reference: '9630', model: 'King Midas', production: '1960s', description: 'Asymmetrical solid gold Midas design dress watch' },
  { family: 'Cellini', reference: '3580', model: 'King Midas', production: '1960s', description: 'Variant angular gold King Midas' },
  { family: 'Cellini', reference: '3581', model: 'Cellini Queen Midas', production: '1960s', description: 'Smaller asymmetric ladies Midas' },
  { family: 'Cellini', reference: '4360', model: 'Cellini Octagon', production: '1970s–1980s', description: 'Octagonal gold dress Cellini' },
  { family: 'Cellini', reference: '5038', model: 'Cellini Midas', production: '1970s–1980s', description: 'Later Midas-style reference' },
  { family: 'Cellini', reference: '50505', model: 'Cellini Time', production: '2014–2022', description: '39mm gold simple 3-hand dress watch' },
  { family: 'Cellini', reference: '50525', model: 'Cellini Dual Time', production: '2014–2022', description: '39mm gold sub-dial second time zone' },
  { family: 'Cellini', reference: '50535', model: 'Cellini Moonphase', production: '2017–present', description: '39mm Everose blue enamel moonphase disc' },

  { family: 'Vintage', reference: '6202', model: 'Turn-O-Graph', production: '1953–1955', description: '36mm rotating bezel sports watch pre-Sub flavor' },
  { family: 'Vintage', reference: '6062', model: 'Oyster Perpetual', production: '1950s', description: '36mm triple-calendar moonphase Stelline' },
  { family: 'Vintage', reference: '8171', model: 'Padellone', production: '1950s', description: '38mm non-Oyster triple-calendar moonphase' },
  { family: 'Vintage', reference: '6238', model: 'Pre-Daytona', production: 'early 1960s', description: '36mm smooth-bezel 3-register chronograph' },
  { family: 'Vintage', reference: '6263 PN', model: 'Cosmograph Daytona "Paul Newman"', production: '1970s–1980s', description: 'Screw-down black bezel Paul Newman dials' },
];

export const ROLEX_REFERENCE_TOTAL = rolexReferences.length;
